all:backtrack.out brute.out

backtrack.o: backtrack.c
	gcc -Wall -c -g backtrack.c

backtrack.out: backtrack.o
	gcc -Wall -g backtrack.o -o backtrack.out

brute.o: brute.c
	gcc -Wall -c -g brute.c

brute.out: brute.o
	gcc -Wall -g brute.o -o brute.out

clean:
	rm -f *.o *.out *~ sivakumar_pa2_stra sivakumar_pa2_tro  sivakumar_pa2_floyd
	rm -f *.save*





